### ISSUE TITLE
Make self-closing-void-elements rule support 'require' option

### ISSUE THREAD

**Issue by ziggythehamster** [rwjblue/ember-template-lint#121]
#16 added the self-closing-void-elements rule. But some of us want the opposite behavior - to require self-closing voids. So, I propose adding `'require'` as an option in addition to `true` and `false`, which does the opposite.

There are a number of reasons why someone might want to use self-closing voids, and I'll try not to argue those in this issue :)

**Comment by rwjblue** [comment]
@ziggythehamster - Seems good to have the option, would love a PR.

**Comment by rwjblue** [comment]
@ziggythehamster - Ping 😸

**Comment by rwjblue** [comment]
Would love this as an option if someone has time to update...

**Comment by rwjblue** [comment]
This was fixed by #247
