### ISSUE TITLE
link-rel-noreferrer

### ISSUE THREAD

**Issue by amk221** [rwjblue/ember-template-lint#139]
I'd like to use the `link-rel-noopener` rule, but in our app we use `rel="noreferrer"` instead.

Is this something you'd consider appropriate to add? If I did a PR?

**Comment by rwjblue** [comment]
I think you can space separate them?

**Comment by amk221** [comment]
I see yes, that would work in that it would prevent `link-rel-noopener` from failing, which is good.
But it would be also better if it could fail if `noreferrer` is missing, as that is the one we require in our app and don't want to be missed-out. thoughts?

**Comment by rwjblue** [comment]
The original bug was fixed in https://github.com/rwjblue/ember-template-lint/pull/106

**Comment by rwjblue** [comment]
Ah, sure. So you want to enforce both. Do they both have the same semantics ( when you use them )?

**Comment by amk221** [comment]
After some digging it seems we use `noreferrer` over `noopener` because it gives you all the benefits of `noopener` but also works for older browsers. `noopener` doesn't work in Firefox.
https://mathiasbynens.github.io/rel-noopener/

**Comment by rwjblue** [comment]
Hmm. Ok, thanks for digging. 

So it seems like we should make both noreferrer and noopener satisfy the rule (though that makes the rule name a bit wrong). Right?

**Comment by rwjblue** [comment]
@cibernox: Thoughts?

**Comment by cibernox** [comment]
My understanding from a 5 minutes read is that `noopener` is more secure than `norreferrer` since the latest prevents to send the `Referrer` headers but still allows access to `window.opener.location`.
Am I wrong?

If so, I'd be a good practice to include both.

**Comment by rwjblue** [comment]
Based on this note [from the spec](https://html.spec.whatwg.org/multipage/semantics.html#link-type-noreferrer):

> For historical reasons, the `noreferrer` keyword implies the behavior associated with the `noopener` keyword when present on a hyperlink that creates a new browsing context. That is, `<a href="..." rel="noreferrer" target="_blank">` has the same behavior as `<a href="..." rel="noreferrer noopener" target="_blank">`.

I think that we should allow either (or make it a configuration value).

**Comment by rwjblue** [comment]
@amk221 - I think we should allow `noreferrer` to pass the current `link-rel-noopener` rule. Would you like to send in a PR for that?

**Comment by rwjblue** [comment]
Note: I'm also in favor of adding a new rule requiring `rel="noreferrer"`, but I still think that the `link-rel-noopener` rule should be satisfied by `noreferrer`.

**Comment by rwjblue** [comment]
I think this was fixed with #143
