### ISSUE TITLE
bare-strings: Getting `Non-translated string used` error for Indian rupee sign `&#8377;`

### ISSUE THREAD

**Issue by MatrixZ** [rwjblue/ember-template-lint#156]
I have configured the `.template-lintrc.js` file with the special characters. Still, I am getting the above error. Please help

**Comment by rwjblue** [comment]
Please submit a failing test ([like this one](https://github.com/rwjblue/ember-template-lint/blob/master/test/unit/rules/lint-bare-strings-test.js#L24-L27)) and we can try to help figure out what is wrong...

**Comment by MatrixZ** [comment]
Added failing test in this PR 
https://github.com/rwjblue/ember-template-lint/pull/157

**Comment by rwjblue** [comment]
Your config needs to whitelist the actual character (not the HTML entity code).

To make this work, you would add `['₹']` as the config itself.

---

**Note:** On my screen the rupee symbol is not displayed above, but that is the actual value within that code snippet.  So basically you need to add the actual rupee symbol in a string by itself to your config...

**Comment by MatrixZ** [comment]
It works when adding a rupee symbol in the config 👍

**Comment by rwjblue** [comment]
Thank you, and I apologize for not realizing this was the issue originally.
