### ISSUE TITLE
Invalid rule configuration found: inline-styles

### ISSUE THREAD

**Issue by kellyselden** [rwjblue/ember-template-lint#168]
I got this message by adding `'inline-styles': true,` to my rules.

**Comment by rwjblue** [comment]
What version are you using?

**Comment by rwjblue** [comment]
Looks like https://github.com/rwjblue/ember-template-lint/pull/149 landed last month but I haven't released yet.

**Comment by kellyselden** [comment]
Resolved in v0.6.4
