### ISSUE TITLE
Can you cut a new release?

### ISSUE THREAD

**Issue by buschtoens** [rwjblue/ember-template-lint#172]
Can you cut a new release with 4eee951f0722a1d0de4a69dc731c5947a0713c76 please?

It upgrades to `glimmer-engine@^0.21.2` which in turn finally gets rid of a qunit version which includes a git dependency, which makes installs behind a corporate proxy impossible.

https://github.com/tildeio/glimmer/commit/2b07fd41b7eda24fe9308ad0477ba36b7e3b8777

Pretty please :heart:

**Comment by rwjblue** [comment]
Release is basically blocked on https://github.com/rwjblue/ember-template-lint/issues/167, and I haven't had enough time to tackle it yet 😢

**Comment by buschtoens** [comment]
Thanks for the quick response. :)

That's very unfortunate. A patch release won't be possible either, maybe cherry-picked?

I'd offer my help for documentation's sake, but I don't think that I have the required level of expertise regarding ember-template-lint. Sorry. :sweat: 

For now we just disabled ember-template-lint at our company. We'll just keep waiting. Please feel no pressure. :smile:

**Comment by kellyselden** [comment]
This is resolved in v0.6.4
