### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by eventualbuddha** [rwjblue/ember-template-lint#189]
Initially I thought it was just #167 that was blocking the release, but then I looked at the [v0.7.0 milestone](https://github.com/rwjblue/ember-template-lint/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.7.0). Do you intend for all of these things to be fixed before the v0.7.0 release? If so, can we help get them done?

cc @mchat

**Comment by eventualbuddha** [comment]
Ping @rwjblue.

**Comment by rwjblue** [comment]
Released 0.7.0-beta.1 now that the major refactoring in https://github.com/rwjblue/ember-template-lint/pull/220 is completed.

**Comment by eventualbuddha** [comment]
cc @mchat

**Comment by initram** [comment]
Should this case not have been closed long ago?

**Comment by rwjblue** [comment]
🎉💃🏾🕺
