### ISSUE TITLE
Report output is not very readable compared to linters like ESLint etc

### ISSUE THREAD

**Issue by pichfl** [rwjblue/ember-template-lint#196]
Maybe support for similar output formatters could be possible?
What would be the best way to tackle this problem? If someone points me in the right direction I'll try to provide this.

**Comment by rwjblue** [comment]
Custom formatters seem like a great idea! 

The main `Linter` returns an array that is later used by [ember-cli-template-lint here](https://github.com/rwjblue/ember-cli-template-lint/blob/35a33b6c06e38b58200e438baaaec5e01322ee3b/broccoli-template-linter.js#L101-L128). We also happen to duplicate that log output logic internally for our command line script [here](https://github.com/rwjblue/ember-template-lint/blob/4fcf6709d5be8bdb7aae531ac7631540121a5f5a/lib/index.js#L149-L161).

**Comment by rwjblue** [comment]
@pichfl - I think this was fixed, right?

(closing for now, will reopen if I'm wrong...)
