### ISSUE TITLE
Option to ignore template files within a folder

### ISSUE THREAD

**Issue by akashdsouza** [rwjblue/ember-template-lint#214]
Instead of matching the moduleId to the exact string, it would be helpful if all templates within a specific directory could be ignored. Something like `app/templates/directory/*`

This could be useful for engines wherein the option is available to ignore all template files within the engine

**Comment by rwjblue** [comment]
Seems like a reasonable capability to add, mind taking a shot at it?

**Comment by akashdsouza** [comment]
Sure

**Comment by rwjblue** [comment]
This was fixed in #218.
