### ISSUE TITLE
Issue with block-indentation rule when used with UTF8-BOM encoding

### ISSUE THREAD

**Issue by initram** [rwjblue/ember-template-lint#215]
For better or worse we are stuck with having byte order mark (BOM) in our template files. 

This causes issues with the block-indentation rule, as it thinks the BOM is a 1 char indent, resulting in errors reported for the closing tag of the first tag in the file. I would hope that it is not a big issue ignoring the BOM or at least stop treating it as whitespace.

**Comment by rwjblue** [comment]
I'll admit to being completely ignorant of BOM and its associated issues, can you submit a failing test PR with an example of how a template would look? You can add one to [this array](https://github.com/rwjblue/ember-template-lint/blob/master/test/unit/rules/lint-block-indentation-test.js#L11-L15), which should fail (in the same way your app templates fail) so we can try to take a look at fixing...

**Comment by rwjblue** [comment]
Resolved by #216
