### ISSUE TITLE
New rule: linebreak-style

### ISSUE THREAD

**Issue by initram** [rwjblue/ember-template-lint#219]
I would love it if this linter also has a linebreak-style rule, like the one found in EsLint: http://eslint.org/docs/rules/linebreak-style

I tried to implement the rule my self, but it seems that the line breaks have already been normalized before the AST is generated, so I could not test for line break style in an AST rule. I think it would require another type of rule, like a raw source rule, or something like that.

**Comment by rwjblue** [comment]
We have access to the raw source, which is what I think we would use for this rule. 

I think it's a great idea!

**Comment by initram** [comment]
I have started working on this. I still need to document it, but it looks promising.

**Comment by rwjblue** [comment]
awesome!

**Comment by initram** [comment]
This issue can now be closed as the pull request have been merged and a new release have been created. When can I expect it to be part of ember-cli-template-lint though?

**Comment by rwjblue** [comment]
You can use the rule already (it was released in 0.8.2).  All you should need to do is update your transient dependencies. For example, if you are using `yarn` you would use `yarn upgrade`.
