### ISSUE TITLE
bare-strings rule crashes on a ConcatStatement in an element attribute

### ISSUE THREAD

**Issue by fhrbek** [rwjblue/ember-template-lint#232]
When linting an element that contains a combination of a string and a variable (ConcatStatement) the linter crashes with an error.

Element example:
```
<input placeholder="{{foo}}X">
```
=>
```
Cannot read property 'indexOf' of undefined
```

This is caused by examining ```node.chars``` for an attribute node that does not contain any characters directly; instead, it's an array of sub-nodes some of which might contain characters (TextNodes).

**Comment by rwjblue** [comment]
Closed by #233
