### ISSUE TITLE
New Rule: No Duplicate attributes

### ISSUE THREAD

**Issue by siva-sundar** [rwjblue/ember-template-lint#251]
Can we have a rule to detect the `duplicate attributes` passed to `Components`, `Helpers` and `Element nodes` ?

**Comment by siva-sundar** [comment]
If its ok, I can raise a PR.

**Comment by rwjblue** [comment]
:+1:

**Comment by rwjblue** [comment]
Implemented in https://github.com/rwjblue/ember-template-lint/pull/252.
