### ISSUE TITLE
"Cannot read property 'slice' of undefined" with the linebreak-style rule

### ISSUE THREAD

**Issue by boris-petrov** [rwjblue/ember-template-lint#253]
When using the new `linebreak-style`, this error occurs - `Cannot read property 'slice' of undefined`. The simplest example of such a template is:

```handlebars
{{#if x}}
  <img src={{some-dir/some-component x}} alt={{alt}}>
{{/if}}
```

**Comment by initram** [comment]
The errors stems from _lib\rules\base.js_ in the function `sourceForNode(node)`.

Here it gets some strange location properties for the mustache statement. The start line is 0 (normally this is 1 indexed). The end line is correctly set as line 1.

Minimal example to reproduce it is:
`<img src={{some-dir/some-component x}}>`

**Comment by rwjblue** [comment]
Thank you for fixing this @initram!
