### ISSUE TITLE
Error: Invalid rule configuration found: template-length

### ISSUE THREAD

**Issue by amyrlam** [rwjblue/ember-template-lint#275]
When I run `yarn run lint`, I get the error `Invalid rule configuration found: template-length`. Seems benign but wondering why?

```
alam@tesla Tango (amy/yarn-lock-fix) $ yarn run lint
yarn run v1.1.0
$ yarn run eslint app tests lib/tango-deploy && yarn run stylelint 'app/styles/**/*.scss' && yarn run ember-template-lint 'app/**/*'
Invalid rule configuration found: template-length
✨  Done in 19.86s.
```

Relates to: https://github.com/rwjblue/ember-template-lint/pull/262 cc @psbanka

**Comment by rwjblue** [comment]
What version of ember-template-lint do you have (`yarn list ember-template-lint`)?

**Comment by amyrlam** [comment]
Thanks for replying and for the help! I'm on the latest, it was https://github.com/psbanka/eslint-plugin-hbs, but @psbanka just fixed it.

```
alam@tesla Tango (peba/fix-inline-checking) $ yarn list ember-template-lint
yarn list v1.1.0
├─ ember-template-lint@0.8.7
└─ eslint-plugin-hbs@0.0.4
   └─ ember-template-lint@0.7.4
✨  Done in 1.18s.
```
