### ISSUE TITLE
Wrong link for table-groups's documentation

### ISSUE THREAD

**Issue by boris-petrov** [rwjblue/ember-template-lint#289]
The link in the [CHANGELOG](https://github.com/rwjblue/ember-template-lint/blob/master/CHANGELOG.md) is broken - it points to a file named `table-groups.md` while the real file has a typo and is named [table-goups.md](https://github.com/rwjblue/ember-template-lint/blob/master/docs/rule/table-goups.md).

**Comment by rwjblue** [comment]
Dangit.  Thats what I get for typing it by hand!

**Comment by boris-petrov** [comment]
We should be glad that `git` copes with renamed files really nicely now. :)

**Comment by rwjblue** [comment]
Fixed by https://github.com/rwjblue/ember-template-lint/commit/3bcc743ea51cfaf29020babc9937a7f75bc201eb...

**Comment by rwjblue** [comment]
Thank you for reporting!
