### ISSUE TITLE
Support global installation

### ISSUE THREAD

**Issue by pswai** [rwjblue/ember-template-lint#309]
I have tried installing `ember-template-lint` globally but it does not work because of missing dependencies. This is because `devDependecies` like `glob` and `strip-bom` are not installed globally. If we make them `dependencies` then it should work.

In fact, they are the modules that make `ember-template-lint` work in production so they really deserve a place in `dependencies` list.

**Comment by rwjblue** [comment]
Absolutely agreed! Sorry about missing this in review!

**Comment by rwjblue** [comment]
The fix was released in v0.8.12, thank you for reporting!
