### ISSUE TITLE
Add `ignore` to config.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-template-lint#32]
To allow completely ignoring certain files.  This would go at the same level as `pending`, and prevent a given file from even being parsed.

**Comment by JackieChiles** [comment]
:+1: from me on this. Currently any referenced engines are linted. It would be nice to be able to ignore those.

**Comment by rwjblue** [comment]
@JackieChiles - It should be straight forward to add if you are interested in a PR...

**Comment by JackieChiles** [comment]
@rwjblue I would be happy to PR. I'll try to work something up and return here if I've got questions :smile:
