### ISSUE TITLE
How can I exclude addons from linting?

### ISSUE THREAD

**Issue by Stanja219** [rwjblue/ember-template-lint#336]
Hello everybody, 
is there a way to exclude certain files or addons from linting?
I tried it with a .template-lintignore file and with ignore: [ /node-modules/*] in the .template-lintrc but both did not work.
Thank you for your help.

**Comment by nexinspiration** [comment]
@Stanja219 

Related Issue: https://github.com/rwjblue/ember-template-lint/issues/119

**Comment by Stanja219** [comment]
Thank you :-)
