### ISSUE TITLE
Rule: Require `rel="noopener"` for any `<a target="_blank"></a>`.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-template-lint#37]
> TL;DR If window.opener is set, a page can trigger a navigation in the opener regardless of security origin. See https://bugs.chromium.org/p/chromium/issues/detail?id=168988 for some background.

General info about `noopener`:

* https://html.spec.whatwg.org/multipage/semantics.html#link-type-noopener
* https://mathiasbynens.github.io/rel-noopener/
* https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
* https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

**Comment by rwjblue** [comment]
I don't have a super strong preference as to whether this should be in `recommended` or not.  Open to thoughts here...

**Comment by oriSomething** [comment]
i think it should be require by default because it can leads to security issues. but maybe we should make two levels:
- for every `target="_blank"`
- only if `target="_blank"` and the `href` it's for absolute URL (i mean high probability which is not the same site)

**Comment by rwjblue** [comment]
Updated description to add a newly released blog post about it:

https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

**Comment by rwjblue** [comment]
Implemented by https://github.com/rwjblue/ember-template-lint/pull/102.
