### ISSUE TITLE
BasePlugin#sourceForNode() adds extra character to qouteless attributes

### ISSUE THREAD

**Issue by oriSomething** [rwjblue/ember-template-lint#40]
i know the [related issues](https://github.com/rwjblue/ember-cli-template-lint/issues/89) closed. but it seems it's not fully fixed. i mean, partly. because when attribute has quotes seems to work fine. only "quote less" attributes have issues

```diff
-    source: "alt=tomster"
+    source: "alt=tomster>"
```

**Comment by rwjblue** [comment]
Awesome, thanks for reporting. I will dig into the htmlbars/glimmer side to see what is going on...

**Comment by rwjblue** [comment]
OK, I think this is fixed now, but you will have to clear node_modules and reinstall. 

Let me know if you are still seeing this issue.
