### ISSUE TITLE
considering using lodash as a dependecy

### ISSUE THREAD

**Issue by oriSomething** [rwjblue/ember-template-lint#43]
it can help us with the ease of creating rules and also with performance.
also `_.chain` method allows to create lazy streams so it's another big boost for performance.

of course it's not a must thing. but since it's not shipped to the browser. adding this library that can improved the code quality is a welcome addition from my side at least

**Comment by rwjblue** [comment]
We already have lodash as a dependency.

**Comment by rwjblue** [comment]
:smiley_cat:

**Comment by oriSomething** [comment]
i missed this 😶
