### ISSUE TITLE
Usage of tabindex=-1 shouldn't be considered as interactive

### ISSUE THREAD

**Issue by boris-petrov** [rwjblue/ember-template-lint#51]
The `nested-interactive` rule is triggered by a `button` inside a `div` with `tabindex=-1`. It shouldn't. We could remove the `tabindex` attribute, however Bootstrap uses this in all examples for modal dialogs.

**Comment by rwjblue** [comment]
Thanks for reporting, I'll try to review the spec to see how it defines tabindex=-1.

**Comment by rwjblue** [comment]
The definition of ["interactive content"](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) says this:

> The tabindex attribute can also make any element into interactive content.

In the definition of [tabindex](https://html.spec.whatwg.org/multipage/interaction.html#attr-tabindex):

> The tabindex content attribute allows authors to indicate that an element is supposed to be focusable, and whether it is supposed to be reachable using sequential focus navigation and, if so, what is to be the relative order of the element for the purposes of sequential focus navigation.

> Positive numbers specify the relative position of the element's focusable areas in the sequential focus navigation order, and negative numbers indicate that the control is to be unreachable by sequential focus navigation.

Then under the further definition of what the meaning of a negative number is:

> The user agent must set the element's tabindex focus flag, but should omit the element from the sequential focus navigation order.

---

Nowhere in the above does it suggest that a `-1` is not an interactive element. It clearly states that setting `tabindex=-1` should mark that element as focused **but** it is not possible to "tab into" via sequential focus navigation.

**Comment by rwjblue** [comment]
@boris-petrov:

> The nested-interactive rule is triggered by a button inside a div with tabindex=-1. It shouldn't. 

Why do you say it shouldn't? Is there a section in the spec that I am missing here?

**Comment by nathanhammond** [comment]
1. `tabindex=-1` is an interactive element, except that `focus` may only be set to it programmatically or via a pointer device. It is a nested interactive element.
2. The Bootstrap example is also correct, the modal should be programmatically focused upon opening and it therefore needs `tabindex=-1`.

The compromise here is probably to not trigger this nested interactive rule for block-level structural elements (e.g. `section`, `article`, `div`) unless they have an `action` attached. Alternatively we lock it out based upon `role=dialog` to scenario-solve.

**Comment by joankaradimov** [comment]
@rwjblue If we assume that the goal of the `nested-interactive` rule is to just disallow nested interactive contents, you are objectively correct. The motivation behind the bug, however, was that the commit that introduces it (https://github.com/rwjblue/ember-template-lint/commit/33c65415e4891fa9f8f72387d46fffb0a861448e) states that its purpose is to avoid "UX problems, accessibility problems, bugs and in some cases to DOM errors"

This specific case does not violate any of those and it's widely used to improve UX and accessibility (without introducing invalid DOM). On the other hand it might just be a better idea to blacklist the tabindex rule on our side (even better - wait for https://github.com/rwjblue/ember-template-lint/pull/50 and use the new syntax)

@nathanhammond These probably make a lot more sense than what was initially suggested. It is much more complex, though. I'm not even sure how this could be configured.
