### ISSUE TITLE
Indentation for empty elements

### ISSUE THREAD

**Issue by amk221** [rwjblue/ember-template-lint#57]
For elements with a lot of attributes, I like to put them on their own line:

```htmlbars
<div
  id="my-button"
  class="button"
  style={{escape "border: 1px solid red"}}
  onclick={{action 'foo'}}
  onmouseover={{action 'bar'}}
  onmouseout={{action 'baz'}}
  tabindex=0
  title="the title"></div>
```

With the above example, I get:
`Expected '</div>'  to be at an indentation of 0 but was found at 20`

I can't suppress the linting error by doing this:

```htmlbars
<div
  ...
  class="button">
  {{~how to suck up whitespace?~}}
</div>
```

**Comment by amk221** [comment]
In fact, I also get this when the element is not empty (unsure what to title this issue?)

```htmlbars
<div
  ...
  class="button">&times;</div>
```

**Comment by rwjblue** [comment]
I'm going to close this one in favor of #63, but I'm thinking/working on a fix...
