### ISSUE TITLE
Textareas display whitespace from block indentation

### ISSUE THREAD

**Issue by binhums** [rwjblue/ember-template-lint#63]
Since textareas are block elements, the linter will instruct the closing tag to match the indentation of the opening tag.

e.g. to change

    <textarea></textarea>

to

    <textarea>
    </textarea>

When this rule is obeyed the textarea will include the added whitespace in the input box.

![image](https://cloud.githubusercontent.com/assets/831043/15585168/e90f3562-2332-11e6-9d33-1bb04de18c15.png)

This took a while to debug :-)

Heres the rule message:

```
block-indentation: Incorrect indentation for `textarea` beginning at L31:C6. Expected `</textarea>` ending at L36:C88 to be at an indentation of 6 but was found at 77.(live-ops/templates/components/new-last-minute-job-form @ L36:C88): 

`<textarea class="form-control"
                id="job-instructions"
                rows="3"
                placeholder="Do it well"
                value={{job.instructions}}
                oninput={{action 'updateInstructions' value='target.value'}}></textarea>`
```

Any ideas for a potential fix? In the mean time I'll disable the rule.

**Comment by binhums** [comment]
Could possibly suggest a tag level whitelist or configuring the `block-indentation` rule to allow close tags on the same line?

**Comment by rwjblue** [comment]
This is related to #57 also (I think they are both about the same issue, but this is focused on `<textarea>`).

**Comment by rwjblue** [comment]
Also, FWIW, `<textarea></textarea>` (open tag and close tag on same line) is actually allowed, but most `<textarea>` usage I have seen is multiple lines for the opening tag. The real issue is the fact that even though there is no space between the open and close tags, they are actually on different lines.

We definitely need to fix, to allow things like:

```hbs
<textarea class="form-control"
                id="job-instructions"
                rows="3"
                placeholder="Do it well"
                value={{job.instructions}}
                oninput={{action 'updateInstructions' value='target.value'}}></textarea>
```

```hbs
<div
  id="my-button"
  class="button"
  style={{escape "border: 1px solid red"}}
  onclick={{action 'foo'}}
  onmouseover={{action 'bar'}}
  onmouseout={{action 'baz'}}
  tabindex=0
  title="the title"></div>
```
