### ISSUE TITLE
Make sure we identify all interactive `role`s.

### ISSUE THREAD

**Issue by nathanhammond** [rwjblue/ember-template-lint#69]

**Comment by rwjblue** [comment]
I believe this was done in https://github.com/rwjblue/ember-template-lint/commit/8647c130b81532d52d34117aa034c8b7209bab56, but please confirm...

**Comment by nathanhammond** [comment]
Whoops, closing. This wasn't the issue placeholder I was supposed to open.

**Comment by rwjblue** [comment]
These are not the droids we are looking for....

**Comment by nathanhammond** [comment]
Reopening! We need to include all of the things which descend from the `widget` abstract role.
https://www.w3.org/TR/wai-aria/roles#widget

For example, we're presently missing:
- `grid`
- `select`
- `tablist`
- ...

Unfortunately it'll probably be easiest to traverse the tree by clicking the subclass roles links starting from here: https://www.w3.org/TR/wai-aria/roles#widget ... if you clear your browser history for that page you can rely on `a:visited` to make sure you got them all. (Good guy CSS making it easy to do a depth-first search!)

**Comment by nathanhammond** [comment]
Actually, you've got this here. Noting this rule for items which implement the `composite` abstract role:

> Authors SHOULD ensure that a composite widget exist as a single navigation stop within the larger navigation system of the web page. Once the composite widget has focus, authors SHOULD provide a separate navigation mechanism for users to navigate to elements that are descendants or owned children of the composite element.`

We'll probably need a separate `composite` list, but we're fine for now.
