### ISSUE TITLE
Enable new rules in recommended config for 0.6.0.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-template-lint#78]
New rules to enable by default:
- `invalid-interactive`
- `img-alt-attributes`
- `style-concatenation`
- `deprecated-inline-view-helper`
- `link-rel-noopener`

New rules needed before releasing:
- [ ] ~~`quotes` (https://github.com/rwjblue/ember-template-lint/pull/42)~~ (punting from 0.6.0 because there is no real progress at the moment, and I'd like to land these other new rules)

**Comment by cibernox** [comment]
Will "link-ref-noopener" be a recommended rule?

**Comment by rwjblue** [comment]
Yes, can you put together a PR for that so I can merge it when I do 0.6.0?
