### ISSUE TITLE
Disallow inline 'style' attribute in html or hbs

### ISSUE THREAD

**Issue by shijistar** [rwjblue/ember-template-lint#97]
Im most projects, we recommend that using css to style the dom elements. But some ones may prefer to write inline style rules, because it's just quick! I would be wonderful if we have a rule that totally disallow inline style rules.

``` css
<div class="navbar" style="margin-bottom: 10px; border: 0;">
...
</div>
```

And it would be even more wonderful if we can add inline directive comment to disable a rule for some rare reasons. I'm not sure if currently we support that.

``` hbs
{{!-- template-lint bare-strings:false --}}
```

**Comment by rwjblue** [comment]
@shijistar - I agree, this would be neat!  You can see just how easy adding a rule is if you take a look at https://github.com/rwjblue/ember-template-lint/pull/111, I would definitely love a rule for this (named `inline-styles`).  Would you like to take a shot at a PR?

**Comment by rwjblue** [comment]
@shijistar - Would love a help on a PR here, if you are up for it...
